<?php defined( '_DOIT' ) or die( 'Restricted access' );

/** Admin "B2B Management" translations (ro/ru/en), modelled on crm_lang.php. */

if (!function_exists('b2b_adm_lang')) {

    function b2b_adm_lang_all(): array
    {
        return [
            'ro' => [
                'module'          => 'Management B2B',
                'tab_users'       => 'Clienți B2B',
                'tab_requests'    => 'Cereri',
                'tab_settings'    => 'Setări',

                // user list
                'users_title'     => 'Clienți B2B',
                'filter_all'      => 'Toate',
                'search'          => 'Caută (login, nume, email, telefon)',
                'col_login'       => 'Login',
                'col_name'        => 'Nume client',
                'col_person_type' => 'Tip',
                'col_contact'     => 'Contact',
                'col_status'      => 'Status',
                'col_regions'     => 'Regiuni',
                'col_last_login'  => 'Ultima autentificare',
                'col_created'     => 'Înregistrat',
                'col_actions'     => 'Acțiuni',
                'open'            => 'Deschide',
                'no_users'        => 'Niciun client B2B înregistrat.',
                'never'           => 'Niciodată',

                // profile
                'profile'         => 'Profil client',
                'tab_data'        => 'Date',
                'tab_perms'       => 'Permisiuni',
                'tab_prices'      => 'Prețuri',
                'prices_hint'     => 'Fiecare tabel de preț se poate personaliza doar pentru acest client. Implicit folosește tabelele globale.',
                'tab_activity'    => 'Istoric acțiuni',
                'tab_invoices'    => 'Conturi de plată',
                'tab_reqs'        => 'Cereri',
                'back_to_list'    => '← Înapoi la listă',

                'person_type'     => 'Tip persoană',
                'pt_company'      => 'Persoană juridică',
                'pt_individual'   => 'Persoană fizică',
                'full_name'       => 'Nume, prenume',
                'company_name'    => 'Denumirea companiei (proformă)',
                'email'           => 'Email',
                'phone'           => 'Telefon',
                'legal_address'   => 'Adresa juridică',
                'bank_name'       => 'Banca',
                'bank_iban'       => 'IBAN',
                'vat_code'        => 'Cod TVA',
                'admin_note'      => 'Notă internă',
                'registered_at'   => 'Data înregistrării',
                'last_ip'         => 'Ultimul IP',

                // actions
                'approve'         => 'Validează contul',
                'call'            => 'Apelează',
                'block'           => 'Blochează',
                'unblock'         => 'Deblochează',
                'delete'          => 'Șterge definitiv',
                'set_password'    => 'Setează parolă nouă',
                'new_password'    => 'Parolă nouă',
                'save'            => 'Salvează',
                'saved'           => 'Modificările au fost salvate.',
                'confirm_delete'  => 'Ștergeți definitiv acest client? Toate datele asociate se pierd.',
                'confirm_block'   => 'Blocați acest client? Sesiunile active vor fi închise.',

                // permissions
                'perms_hint'      => 'Bifați ce poate vedea clientul. Ce e debifat nu apare în catalog și returnează „Restricționat conform planului B2B" la accesul direct.',
                'perms_regions'   => 'Regiuni',
                'perms_catalog'   => 'Tip catalog',
                'cat_in_stock'    => 'În stoc',
                'cat_on_order'    => 'La comandă',

                // requests
                'requests_title'  => 'Conturi de plată',
                'col_client'      => 'Client',
                'col_car'         => 'Mașină',
                'col_invoice'     => 'Proformă',
                'col_advance'     => 'Avans',
                'col_comment'     => 'Comentariu',
                'col_date'        => 'Data',
                'no_requests'     => 'Nicio cerere înregistrată.',
                'mark_seen'       => 'Marchează văzută',
                'mark_approved'   => 'Aprobă',
                'mark_rejected'   => 'Respinge',

                // settings
                'settings_title'  => 'Setări modul B2B',
                'pricing_title'   => 'Prețuri B2B',
                'pricing_hint'    => 'Aceleași tabele ca la prețul public, dar valorile de aici se aplică doar clienților B2B logați. Markup-ul Coreea, vama și cursul rămân comune.',
                'pricing_commission' => 'Comision sauto (Europa + Coreea + SUA)',
                'pricing_delivery'   => 'Transport — Europa',
                'pricing_eu_params'  => 'Cheltuieli — Europa',
                'pricing_kr_params'  => 'Cheltuieli — Coreea',
                'pricing_us_params'  => 'Cheltuieli — SUA',
                'ignore_personal_title' => 'Oprește termenele individuale',
                'ignore_personal_hint'  => 'Când e pornit, termenul propriu al fiecărui client este ignorat și rămâne valabil doar termenul ofertei generale. Nu șterge datele: la oprire, fiecare client își recapătă termenul lui.',
                'ignore_personal_on'    => 'Termenele individuale sunt ignorate — decide doar oferta generală.',
                'ignore_personal_off'   => 'Termenele individuale sunt din nou active.',
                'pricing_not_migrated' => 'Tabelele de prețuri B2B nu există încă. Rulați sql_scripts/create_b2b_tables.sql.',
                'pricing_public'   => 'Public (nelogați)',
                'pricing_off'      => 'oprit',
                'pricing_title_user' => 'Prețuri individuale —',
                'pricing_hint_user'  => 'Prețurile de aici se aplică DOAR acestui client. Un tabel lăsat „Global" folosește prețurile comune; salvează-l ca să-l personalizezi. „Revenire la global" șterge versiunea lui.',
                'pricing_global_b2b' => 'Global B2B',
                'pricing_tag_custom' => 'Individual',
                'pricing_tag_global' => 'Global',
                'pricing_reset'      => 'Revenire la global',
                'pricing_reset_done' => 'Revii la prețurile globale pentru acest tabel?',

                // offer deadline (timer)
                'offer_title'      => 'Termenul ofertei',
                'offer_hint'       => 'Data până la care sunt valabile prețurile B2B generale. Când expiră, toți partenerii văd prețurile publice. Gol = fără termen.',
                'offer_hint_user'  => 'Termen doar pentru acest client. Când expiră, el trece pe prețurile globale B2B (nu pe cele publice). Gol = urmează termenul general.',
                'offer_until'      => 'Valabilă până la',
                'offer_ph'         => 'zz.ll.aaaa --:--',
                'offer_none'       => 'Fără termen',
                'offer_global_ref' => 'Termen general',
                'offer_expired'    => 'Expirată',
                'offer_left'       => 'Timp rămas',

                // gifts
                'cancel'           => 'Anulează',
                'gift_send'        => 'Trimite cadou',
                'gift_title'       => 'Trimite cadou',
                'gift_hint'        => 'Alege serviciile oferite. Clientul le vede imediat în cabinetul lui, cu o notificare.',
                'gift_note'        => 'Observații (opțional)',
                'gift_sent'        => 'Cadoul a fost trimis.',
                'gift_empty'       => 'Alege cel puțin un serviciu sau scrie o observație.',
                'gift_revoke'      => 'Retrage',
                'gift_revoked'     => 'Cadoul a fost retras.',
                'gift_confirm_rev' => 'Retragi acest cadou? Clientul nu îl va mai vedea.',
                'gift_none'        => 'Niciun cadou trimis.',
                'gift_list_title'  => 'Cadouri trimise',
                'gift_st_new'      => 'Nevăzut',
                'gift_st_seen'     => 'Văzut',
                'gift_st_revoked'  => 'Retras',

                // activity history
                'hist_open'        => 'Istoric',
                'hist_title'       => 'Istoric',
                'hist_none'        => 'Nicio activitate înregistrată.',
                'hist_when'        => 'Ora',
                'hist_source'      => 'Sursă',
                'hist_cars_seen'   => 'Mașini vizitate',
                'hist_last_login'  => 'Ultima autentificare',
                'hist_car'         => 'Mașina',
                'hist_price'       => 'Preț',
                'hist_times'       => 'De câte ori a revenit la această mașină',
                'hist_sources'     => 'Surse preferate',
                'hist_src_stock'   => 'Stoc propriu',

                // action labels in the log
                'act_login'               => 'Autentificare',
                'act_login_failed'        => 'Autentificare eșuată',
                'act_logout'              => 'Deconectare',
                'act_page_view'           => 'A vizitat mașina',
                'act_generate_invoice'    => 'A generat cont de plată',
                'act_send_to_admin'       => 'A trimis cerere',
                'act_region_denied'       => 'Acces regiune refuzat',
                'act_save_car'            => 'A salvat mașina',
                'act_unsave_car'          => 'A scos din salvate',
                'act_register'            => 'Înregistrare',
                'act_password_reset'      => 'Resetare parolă',
                'act_status_changed'      => 'Status schimbat',
                'act_permissions_changed' => 'Permisiuni schimbate',
                'act_gift_sent'           => 'A primit cadou',
                'act_gift_revoked'        => 'Cadou retras',
                'prices_has_custom'  => 'Acest client are prețuri individuale.',
                'prices_all_global'  => 'Acest client folosește prețurile globale.',
                'prices_open_editor' => 'Deschide editorul de prețuri →',
                'admin_section'   => 'Super Admin',
                'admin_hint'      => 'Al doilea telefon/email e opțional. Notificarea WhatsApp ajunge la fiecare număr completat.',
                'admin_recipient' => 'Destinatar',
                'optional'        => 'opțional',
                'invoice_section' => 'Proforme',
                'advance_default' => 'Avans minim / sumă fixă (MDL)',
                'advance_mode'    => 'Mod de calcul',
                'advance_mode_fixed'   => 'Sumă fixă',
                'advance_mode_percent' => 'Procent din prețul mașinii',
                'advance_percent' => 'Procent (%)',
                'advance_max'     => 'Plafon maxim (EUR, 0 = fără)',
                'advance_hint'    => 'Valoarea sugerată în panoul de pe pagina mașinii. Clientul o poate modifica manual înainte de a genera proforma. În mod procentual, suma fixă devine pragul minim.',

                // statuses
                'st_pending'      => 'În așteptare',
                'st_active'       => 'Activ',
                'st_blocked'      => 'Blocat',
                'st_new'          => 'Nouă',
                'st_seen'         => 'Văzută',
                'st_approved'     => 'Aprobată',
                'st_rejected'     => 'Respinsă',
                'st_issued'       => 'Emis',
                'st_sent'         => 'Transmis',
                'st_paid'         => 'Achitat',
                'st_cancelled'    => 'Anulat',

                'rg_korea'        => 'Coreea',
                'rg_europe'       => 'Europa',
                'rg_china'        => 'China',
                'rg_canada'          => 'Canada',

                'ac_login'               => 'Autentificare',
                'ac_login_failed'        => 'Autentificare eșuată',
                'ac_logout'              => 'Ieșire din cont',
                'ac_page_view'           => 'Vizualizare mașină',
                'ac_generate_invoice'    => 'Generare cont de plată',
                'ac_send_to_admin'       => 'Cerere către Super Admin',
                'ac_region_denied'       => 'Acces refuzat pe regiune',
                'ac_save_car'            => 'Mașină salvată',
                'ac_unsave_car'          => 'Mașină eliminată',
                'ac_register'            => 'Cont creat',
                'ac_password_reset'      => 'Parolă schimbată',
                'ac_status_changed'      => 'Status modificat',
                'ac_permissions_changed' => 'Permisiuni modificate',

                'col_action'      => 'Acțiune',
                'col_details'     => 'Detalii',
                'col_ip'          => 'IP',
                'no_activity'     => 'Nicio activitate înregistrată.',
                'no_invoices'     => 'Niciun cont de plată generat.',
            ],

            'ru' => [
                'module'          => 'Управление B2B',
                'tab_users'       => 'Клиенты B2B',
                'tab_requests'    => 'Заявки',
                'tab_settings'    => 'Настройки',

                'users_title'     => 'Клиенты B2B',
                'filter_all'      => 'Все',
                'search'          => 'Поиск (логин, имя, email, телефон)',
                'col_login'       => 'Логин',
                'col_name'        => 'Имя клиента',
                'col_person_type' => 'Тип',
                'col_contact'     => 'Контакт',
                'col_status'      => 'Статус',
                'col_regions'     => 'Регионы',
                'col_last_login'  => 'Последний вход',
                'col_created'     => 'Регистрация',
                'col_actions'     => 'Действия',
                'open'            => 'Открыть',
                'no_users'        => 'Нет зарегистрированных клиентов B2B.',
                'never'           => 'Никогда',

                'profile'         => 'Профиль клиента',
                'tab_data'        => 'Данные',
                'tab_perms'       => 'Права',
                'tab_prices'      => 'Цены',
                'prices_hint'     => 'Каждую таблицу цен можно настроить только для этого клиента. По умолчанию используются глобальные таблицы.',
                'tab_activity'    => 'История действий',
                'tab_invoices'    => 'Счета на оплату',
                'tab_reqs'        => 'Заявки',
                'back_to_list'    => '← Назад к списку',

                'person_type'     => 'Тип лица',
                'pt_company'      => 'Юридическое лицо',
                'pt_individual'   => 'Физическое лицо',
                'full_name'       => 'Имя, фамилия',
                'company_name'    => 'Название компании (проформа)',
                'email'           => 'Email',
                'phone'           => 'Телефон',
                'legal_address'   => 'Юридический адрес',
                'bank_name'       => 'Банк',
                'bank_iban'       => 'IBAN',
                'vat_code'        => 'Код НДС',
                'admin_note'      => 'Внутренняя заметка',
                'registered_at'   => 'Дата регистрации',
                'last_ip'         => 'Последний IP',

                'approve'         => 'Подтвердить аккаунт',
                'call'            => 'Позвонить',
                'block'           => 'Заблокировать',
                'unblock'         => 'Разблокировать',
                'delete'          => 'Удалить навсегда',
                'set_password'    => 'Задать новый пароль',
                'new_password'    => 'Новый пароль',
                'save'            => 'Сохранить',
                'saved'           => 'Изменения сохранены.',
                'confirm_delete'  => 'Удалить клиента навсегда? Все связанные данные будут потеряны.',
                'confirm_block'   => 'Заблокировать клиента? Активные сессии будут закрыты.',

                'perms_hint'      => 'Отметьте, что доступно клиенту. Неотмеченное не показывается в каталоге и возвращает «Ограничено согласно B2B-плану» при прямом доступе.',
                'perms_regions'   => 'Регионы',
                'perms_catalog'   => 'Тип каталога',
                'cat_in_stock'    => 'В наличии',
                'cat_on_order'    => 'Под заказ',

                'requests_title'  => 'Счета на оплату',
                'col_client'      => 'Клиент',
                'col_car'         => 'Автомобиль',
                'col_invoice'     => 'Счёт',
                'col_advance'     => 'Аванс',
                'col_comment'     => 'Комментарий',
                'col_date'        => 'Дата',
                'no_requests'     => 'Заявок нет.',
                'mark_seen'       => 'Отметить просмотренной',
                'mark_approved'   => 'Одобрить',
                'mark_rejected'   => 'Отклонить',

                'settings_title'  => 'Настройки модуля B2B',
                'pricing_title'   => 'Цены B2B',
                'pricing_hint'    => 'Те же таблицы, что и для публичной цены, но эти значения применяются только к вошедшим B2B-клиентам. Наценка Кореи, растаможка и курс остаются общими.',
                'pricing_commission' => 'Комиссия sauto (Европа + Корея + США)',
                'pricing_delivery'   => 'Доставка — Европа',
                'pricing_eu_params'  => 'Расходы — Европа',
                'pricing_kr_params'  => 'Расходы — Корея',
                'pricing_us_params'  => 'Расходы — США',
                'ignore_personal_title' => 'Отключить индивидуальные сроки',
                'ignore_personal_hint'  => 'Когда включено, собственный срок каждого клиента игнорируется и действует только срок общего предложения. Данные не удаляются: при выключении каждый клиент снова получает свой срок.',
                'ignore_personal_on'    => 'Индивидуальные сроки игнорируются — решает только общее предложение.',
                'ignore_personal_off'   => 'Индивидуальные сроки снова активны.',
                'pricing_not_migrated' => 'Таблицы цен B2B ещё не созданы. Выполните sql_scripts/create_b2b_tables.sql.',
                'pricing_public'   => 'Публичная (без входа)',
                'pricing_off'      => 'выкл',
                'pricing_title_user' => 'Индивидуальные цены —',
                'pricing_hint_user'  => 'Эти цены применяются ТОЛЬКО к этому клиенту. Таблица со статусом «Глобально» использует общие цены; сохраните её, чтобы задать индивидуальные. «Вернуть к глобальным» удаляет его версию.',
                'pricing_global_b2b' => 'Глобальная B2B',
                'pricing_tag_custom' => 'Индивидуально',
                'pricing_tag_global' => 'Глобально',
                'pricing_reset'      => 'Вернуть к глобальным',
                'pricing_reset_done' => 'Вернуть глобальные цены для этой таблицы?',

                // offer deadline (timer)
                'offer_title'      => 'Срок предложения',
                'offer_hint'       => 'Дата, до которой действуют общие цены B2B. После истечения все партнёры видят публичные цены. Пусто = без срока.',
                'offer_hint_user'  => 'Срок только для этого клиента. После истечения он переходит на глобальные цены B2B (не на публичные). Пусто = действует общий срок.',
                'offer_until'      => 'Действует до',
                'offer_ph'         => 'дд.мм.гггг --:--',
                'offer_none'       => 'Без срока',
                'offer_global_ref' => 'Общий срок',
                'offer_expired'    => 'Истекло',
                'offer_left'       => 'Осталось',

                // gifts
                'cancel'           => 'Отмена',
                'gift_send'        => 'Отправить подарок',
                'gift_title'       => 'Отправить подарок',
                'gift_hint'        => 'Выберите услуги. Клиент сразу увидит их в своём кабинете, с уведомлением.',
                'gift_note'        => 'Примечание (необязательно)',
                'gift_sent'        => 'Подарок отправлен.',
                'gift_empty'       => 'Выберите хотя бы одну услугу или напишите примечание.',
                'gift_revoke'      => 'Отозвать',
                'gift_revoked'     => 'Подарок отозван.',
                'gift_confirm_rev' => 'Отозвать этот подарок? Клиент его больше не увидит.',
                'gift_none'        => 'Подарки не отправлялись.',
                'gift_list_title'  => 'Отправленные подарки',
                'gift_st_new'      => 'Не просмотрен',
                'gift_st_seen'     => 'Просмотрен',
                'gift_st_revoked'  => 'Отозван',

                // activity history
                'hist_open'        => 'История',
                'hist_title'       => 'История',
                'hist_none'        => 'Активность не зафиксирована.',
                'hist_when'        => 'Время',
                'hist_source'      => 'Источник',
                'hist_cars_seen'   => 'Просмотрено авто',
                'hist_last_login'  => 'Последний вход',
                'hist_car'         => 'Автомобиль',
                'hist_price'       => 'Цена',
                'hist_times'       => 'Сколько раз возвращался к этому авто',
                'hist_sources'     => 'Любимые источники',
                'hist_src_stock'   => 'Свой склад',

                // action labels in the log
                'act_login'               => 'Вход',
                'act_login_failed'        => 'Неудачный вход',
                'act_logout'              => 'Выход',
                'act_page_view'           => 'Смотрел авто',
                'act_generate_invoice'    => 'Создал счёт',
                'act_send_to_admin'       => 'Отправил заявку',
                'act_region_denied'       => 'Отказ по региону',
                'act_save_car'            => 'Добавил в избранное',
                'act_unsave_car'          => 'Убрал из избранного',
                'act_register'            => 'Регистрация',
                'act_password_reset'      => 'Сброс пароля',
                'act_status_changed'      => 'Статус изменён',
                'act_permissions_changed' => 'Права изменены',
                'act_gift_sent'           => 'Получил подарок',
                'act_gift_revoked'        => 'Подарок отозван',
                'prices_has_custom'  => 'У клиента есть индивидуальные цены.',
                'prices_all_global'  => 'Клиент использует глобальные цены.',
                'prices_open_editor' => 'Открыть редактор цен →',
                'admin_section'   => 'Супер Админ',
                'admin_hint'      => 'Второй телефон/email необязателен. Уведомление WhatsApp придёт на каждый заполненный номер.',
                'admin_recipient' => 'Получатель',
                'optional'        => 'необязательно',
                'invoice_section' => 'Счета',
                'advance_default' => 'Минимальный / фиксированный аванс (MDL)',
                'advance_mode'    => 'Способ расчёта',
                'advance_mode_fixed'   => 'Фиксированная сумма',
                'advance_mode_percent' => 'Процент от цены авто',
                'advance_percent' => 'Процент (%)',
                'advance_max'     => 'Максимум (EUR, 0 = без)',
                'advance_hint'    => 'Значение, предлагаемое на странице авто. Клиент может изменить его вручную. В процентном режиме фиксированная сумма служит нижним порогом.',

                'st_pending'      => 'Ожидает',
                'st_active'       => 'Активен',
                'st_blocked'      => 'Заблокирован',
                'st_new'          => 'Новая',
                'st_seen'         => 'Просмотрена',
                'st_approved'     => 'Одобрена',
                'st_rejected'     => 'Отклонена',
                'st_issued'       => 'Выставлен',
                'st_sent'         => 'Отправлен',
                'st_paid'         => 'Оплачен',
                'st_cancelled'    => 'Отменён',

                'rg_korea'        => 'Корея',
                'rg_europe'       => 'Европа',
                'rg_china'        => 'Китай',
                'rg_canada'          => 'Канада',

                'ac_login'               => 'Вход',
                'ac_login_failed'        => 'Неудачный вход',
                'ac_logout'              => 'Выход',
                'ac_page_view'           => 'Просмотр авто',
                'ac_generate_invoice'    => 'Создание счёта',
                'ac_send_to_admin'       => 'Заявка Супер Админу',
                'ac_region_denied'       => 'Отказ по региону',
                'ac_save_car'            => 'Авто сохранено',
                'ac_unsave_car'          => 'Авто удалено',
                'ac_register'            => 'Аккаунт создан',
                'ac_password_reset'      => 'Пароль изменён',
                'ac_status_changed'      => 'Статус изменён',
                'ac_permissions_changed' => 'Права изменены',

                'col_action'      => 'Действие',
                'col_details'     => 'Детали',
                'col_ip'          => 'IP',
                'no_activity'     => 'Активность не зафиксирована.',
                'no_invoices'     => 'Счета не создавались.',
            ],

            'en' => [
                'module'          => 'B2B Management',
                'tab_users'       => 'B2B clients',
                'tab_requests'    => 'Requests',
                'tab_settings'    => 'Settings',

                'users_title'     => 'B2B clients',
                'filter_all'      => 'All',
                'search'          => 'Search (login, name, email, phone)',
                'col_login'       => 'Login',
                'col_name'        => 'Client name',
                'col_person_type' => 'Type',
                'col_contact'     => 'Contact',
                'col_status'      => 'Status',
                'col_regions'     => 'Regions',
                'col_last_login'  => 'Last login',
                'col_created'     => 'Registered',
                'col_actions'     => 'Actions',
                'open'            => 'Open',
                'no_users'        => 'No B2B client registered.',
                'never'           => 'Never',

                'profile'         => 'Client profile',
                'tab_data'        => 'Details',
                'tab_perms'       => 'Permissions',
                'tab_prices'      => 'Prices',
                'prices_hint'     => 'Each price table can be customised for this client only. By default it uses the global tables.',
                'tab_activity'    => 'Activity log',
                'tab_invoices'    => 'Payment invoices',
                'tab_reqs'        => 'Requests',
                'back_to_list'    => '← Back to list',

                'person_type'     => 'Person type',
                'pt_company'      => 'Legal entity',
                'pt_individual'   => 'Individual',
                'full_name'       => 'Full name',
                'company_name'    => 'Company name (proforma)',
                'email'           => 'Email',
                'phone'           => 'Phone',
                'legal_address'   => 'Legal address',
                'bank_name'       => 'Bank',
                'bank_iban'       => 'IBAN',
                'vat_code'        => 'VAT code',
                'admin_note'      => 'Internal note',
                'registered_at'   => 'Registration date',
                'last_ip'         => 'Last IP',

                'approve'         => 'Approve account',
                'call'            => 'Call',
                'block'           => 'Block',
                'unblock'         => 'Unblock',
                'delete'          => 'Delete permanently',
                'set_password'    => 'Set new password',
                'new_password'    => 'New password',
                'save'            => 'Save',
                'saved'           => 'Changes saved.',
                'confirm_delete'  => 'Permanently delete this client? All related data is lost.',
                'confirm_block'   => 'Block this client? Active sessions will be terminated.',

                'perms_hint'      => 'Tick what the client may see. Unticked items are hidden from the catalog and return "Restricted by your B2B plan" on direct access.',
                'perms_regions'   => 'Regions',
                'perms_catalog'   => 'Catalog type',
                'cat_in_stock'    => 'In stock',
                'cat_on_order'    => 'On order',

                'requests_title'  => 'Payment invoices',
                'col_client'      => 'Client',
                'col_car'         => 'Car',
                'col_invoice'     => 'Invoice',
                'col_advance'     => 'Advance',
                'col_comment'     => 'Comment',
                'col_date'        => 'Date',
                'no_requests'     => 'No request recorded.',
                'mark_seen'       => 'Mark as seen',
                'mark_approved'   => 'Approve',
                'mark_rejected'   => 'Reject',

                'settings_title'  => 'B2B module settings',
                'pricing_title'   => 'B2B pricing',
                'pricing_hint'    => 'The same tables as the public price, but these values apply only to logged-in B2B clients. Korea markup, customs and the FX rate stay shared.',
                'pricing_commission' => 'sauto commission (Europe + Korea + USA)',
                'pricing_delivery'   => 'Delivery — Europe',
                'pricing_eu_params'  => 'Costs — Europe',
                'pricing_kr_params'  => 'Costs — Korea',
                'pricing_us_params'  => 'Costs — USA',
                'ignore_personal_title' => 'Suspend individual deadlines',
                'ignore_personal_hint'  => 'While on, every partner\'s own deadline is ignored and only the general offer applies. Nothing is deleted: switch it off and each of them gets their own deadline back.',
                'ignore_personal_on'    => 'Individual deadlines are ignored — the general offer decides.',
                'ignore_personal_off'   => 'Individual deadlines are active again.',
                'pricing_not_migrated' => 'The B2B pricing tables do not exist yet. Run sql_scripts/create_b2b_tables.sql.',
                'pricing_public'   => 'Public (guest)',
                'pricing_off'      => 'off',
                'pricing_title_user' => 'Individual pricing —',
                'pricing_hint_user'  => 'These prices apply ONLY to this client. A table left "Global" uses the shared prices; save it to customise. "Back to global" removes their version.',
                'pricing_global_b2b' => 'Global B2B',
                'pricing_tag_custom' => 'Individual',
                'pricing_tag_global' => 'Global',
                'pricing_reset'      => 'Back to global',
                'pricing_reset_done' => 'Revert this table to the global prices?',

                // offer deadline (timer)
                'offer_title'      => 'Offer deadline',
                'offer_hint'       => 'The date the general B2B prices are valid until. Once it passes, every partner sees the public prices. Empty = no limit.',
                'offer_hint_user'  => 'A deadline for this client only. Once it passes they move to the global B2B prices (not the public ones). Empty = the general deadline applies.',
                'offer_until'      => 'Valid until',
                'offer_ph'         => 'dd.mm.yyyy --:--',
                'offer_none'       => 'No deadline',
                'offer_global_ref' => 'General deadline',
                'offer_expired'    => 'Expired',
                'offer_left'       => 'Time left',

                // gifts
                'cancel'           => 'Cancel',
                'gift_send'        => 'Send gift',
                'gift_title'       => 'Send gift',
                'gift_hint'        => 'Pick the services offered. The client sees them in their cabinet straight away, with a notification.',
                'gift_note'        => 'Note (optional)',
                'gift_sent'        => 'Gift sent.',
                'gift_empty'       => 'Pick at least one service or write a note.',
                'gift_revoke'      => 'Withdraw',
                'gift_revoked'     => 'Gift withdrawn.',
                'gift_confirm_rev' => 'Withdraw this gift? The client will no longer see it.',
                'gift_none'        => 'No gifts sent.',
                'gift_list_title'  => 'Gifts sent',
                'gift_st_new'      => 'Unseen',
                'gift_st_seen'     => 'Seen',
                'gift_st_revoked'  => 'Withdrawn',

                // activity history
                'hist_open'        => 'History',
                'hist_title'       => 'History',
                'hist_none'        => 'No activity recorded.',
                'hist_when'        => 'Time',
                'hist_source'      => 'Source',
                'hist_cars_seen'   => 'Cars viewed',
                'hist_last_login'  => 'Last login',
                'hist_car'         => 'Car',
                'hist_price'       => 'Price',
                'hist_times'       => 'How many times he came back to this car',
                'hist_sources'     => 'Preferred sources',
                'hist_src_stock'   => 'Own stock',

                // action labels in the log
                'act_login'               => 'Login',
                'act_login_failed'        => 'Failed login',
                'act_logout'              => 'Logout',
                'act_page_view'           => 'Viewed car',
                'act_generate_invoice'    => 'Generated invoice',
                'act_send_to_admin'       => 'Sent request',
                'act_region_denied'       => 'Region denied',
                'act_save_car'            => 'Saved car',
                'act_unsave_car'          => 'Unsaved car',
                'act_register'            => 'Registration',
                'act_password_reset'      => 'Password reset',
                'act_status_changed'      => 'Status changed',
                'act_permissions_changed' => 'Permissions changed',
                'act_gift_sent'           => 'Received gift',
                'act_gift_revoked'        => 'Gift withdrawn',
                'prices_has_custom'  => 'This client has individual prices.',
                'prices_all_global'  => 'This client uses the global prices.',
                'prices_open_editor' => 'Open the pricing editor →',
                'admin_section'   => 'Super Admin',
                'admin_hint'      => 'The second phone/email is optional. The WhatsApp notification reaches every number you fill in.',
                'admin_recipient' => 'Recipient',
                'optional'        => 'optional',
                'invoice_section' => 'Invoices',
                'advance_default' => 'Minimum / fixed advance (MDL)',
                'advance_mode'    => 'Calculation mode',
                'advance_mode_fixed'   => 'Fixed amount',
                'advance_mode_percent' => 'Percentage of car price',
                'advance_percent' => 'Percentage (%)',
                'advance_max'     => 'Cap (EUR, 0 = none)',
                'advance_hint'    => 'Value prefilled in the panel on the car page. The client can override it before generating the proforma. In percentage mode the fixed amount acts as the floor.',

                'st_pending'      => 'Pending',
                'st_active'       => 'Active',
                'st_blocked'      => 'Blocked',
                'st_new'          => 'New',
                'st_seen'         => 'Seen',
                'st_approved'     => 'Approved',
                'st_rejected'     => 'Rejected',
                'st_issued'       => 'Issued',
                'st_sent'         => 'Sent',
                'st_paid'         => 'Paid',
                'st_cancelled'    => 'Cancelled',

                'rg_korea'        => 'Korea',
                'rg_europe'       => 'Europe',
                'rg_china'        => 'China',
                'rg_canada'          => 'Canada',

                'ac_login'               => 'Login',
                'ac_login_failed'        => 'Failed login',
                'ac_logout'              => 'Logout',
                'ac_page_view'           => 'Car viewed',
                'ac_generate_invoice'    => 'Invoice generated',
                'ac_send_to_admin'       => 'Request to Super Admin',
                'ac_region_denied'       => 'Region access denied',
                'ac_save_car'            => 'Car saved',
                'ac_unsave_car'          => 'Car removed',
                'ac_register'            => 'Account created',
                'ac_password_reset'      => 'Password changed',
                'ac_status_changed'      => 'Status changed',
                'ac_permissions_changed' => 'Permissions changed',

                'col_action'      => 'Action',
                'col_details'     => 'Details',
                'col_ip'          => 'IP',
                'no_activity'     => 'No activity recorded.',
                'no_invoices'     => 'No invoice generated.',
            ],
        ];
    }

    function b2b_adm_lang(?string $lang = null): array
    {
        $lang = $lang ?? ($_COOKIE['lang'] ?? 'ro');
        $all  = b2b_adm_lang_all();
        return $all[$lang] ?? $all['ro'];
    }

    /** One HTML-escaped string. */
    function b2b_adm_t(string $key, ?string $lang = null): string
    {
        $t = b2b_adm_lang($lang);
        return htmlspecialchars($t[$key] ?? $key, ENT_QUOTES, 'UTF-8');
    }

    function b2b_adm_esc($value): string
    {
        return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
    }

    /** Handset for the "call this client" action. */
    function b2b_adm_phone_icon(): string
    {
        return '<svg class="b2ba-btn__i" viewBox="0 0 24 24" fill="none" stroke="currentColor"'
             . ' stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
             . '<path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1.9.4 1.8.7 2.7a2 2 0 0 1-.5 2.1L8.1 9.9a16 16 0 0 0 6 6l1.4-1.2a2 2 0 0 1 2.1-.5c.9.3 1.8.6 2.7.7a2 2 0 0 1 1.7 2z"></path>'
             . '</svg>';
    }

    /** Padlock marking a field the admin may read but never change. */
    function b2b_adm_lock_icon(): string
    {
        return '<svg class="b2ba-locked__i" viewBox="0 0 24 24" fill="none" stroke="currentColor"'
             . ' stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
             . '<rect x="4" y="11" width="16" height="10" rx="2"></rect>'
             . '<path d="M8 11V7a4 4 0 0 1 8 0v4"></path>'
             . '</svg>';
    }
}
