<?php defined( '_DOIT' ) or die( 'Restricted access' );

$lang_code = isset($_COOKIE['lang']) ? $_COOKIE['lang'] : 'ro';

$calc_trans = [
    'ro' => [
        // Calculator page
        'title' => 'Calculator Vămuire Auto',
        'eur_rate_label' => 'Curs 1 EUR =',
        'eur_rate_mdl' => 'MDL',
        'save' => 'Salvează',
        'rate_saved_btn' => 'Salvat',
        'rate_error_btn' => 'Eroare',
        'vehicle_type' => 'Tipul vehiculului',
        'car' => 'Autoturism',
        'motorcycle' => 'Motocicletă',
        'truck' => 'Camion',
        'year' => 'Anul producerii',
        'capacity' => 'Capacitatea cilindrică (cm³)',
        'capacity_placeholder' => 'ex: 1998',
        'price_eur' => 'Prețul vehiculului (EUR)',
        'price_placeholder' => 'ex: 15000',
        'transport_price' => 'Preț transport (EUR)',
        'transport_placeholder' => 'ex: 500',
        'fuel_type' => 'Tipul combustibilului',
        'gasoline' => 'Benzină',
        'diesel' => 'Diesel',
        'hybrid' => 'Hybrid',
        'electric' => 'Electric',
        'plugin_hybrid' => 'Plug-in Hybrid',
        'full_hybrid' => 'Full Hybrid',
        'mild_hybrid' => 'Mild Hybrid (fără reducere)',
        'calculate' => 'Calculează',
        'results' => 'Rezultatul calculului',
        'value_mdl' => 'Valoarea în vamă (MDL)',
        'excise' => 'Acciza',
        'luxury_excise' => 'Acciză lux',
        'tva' => 'TVA',
        'customs_duty' => 'Taxă proceduri vamale',
        'damage_protection' => 'Protecție împotriva daunelor (1,2%)',
        'total' => 'TOTAL COSTURI VĂMUIRE',
        'vehicle_total' => 'SUMA TOTALĂ VEHICUL',
        'electric_notice' => 'Vehiculele electrice sunt scutite de accize!',
        'electric_notice_sub' => 'Se achită doar TVA la valoarea în vamă.',
        'usage_stats' => 'Statistici utilizare',
        'edit_rates' => 'Editare cote accize',
        
        // Usage page
        'usage_title' => 'Statistici Utilizare Calculator',
        'back_to_calc' => '← Înapoi la Calculator',
        'select_date' => 'Selectează data',
        'no_usage_data' => 'Nu există date de utilizare',
        'user' => 'Utilizator',
        'total_uses' => 'Total utilizări',
        'last_use' => 'Ultima utilizare',
        
        // Rates page
        'rates_title' => 'Editare Cote Accize',
        'general_settings' => 'Setări Generale',
        'gasoline_rates' => 'Cote Accize - Benzină (MDL/cm³)',
        'diesel_rates' => 'Cote Accize - Diesel (MDL/cm³)',
        'motorcycle_rates' => 'Cote Accize - Motociclete (MDL/cm³)',
        'capacity_min' => 'Capacitate Min (cm³)',
        'capacity_max' => 'Capacitate Max (cm³)',
        'age_min' => 'Vârstă Min (ani)',
        'age_max' => 'Vârstă Max (ani)',
        'rate' => 'Cotă (MDL/cm³)',
        'save_changes' => 'Salvează modificările',
        'save_success' => 'Modificările au fost salvate cu succes!',
        'save_error' => 'Eroare la salvare!',
        
        // Settings labels
        'setting_tva_rate' => 'Cota TVA',
        'setting_tva_rate_desc' => 'Cota TVA în procente',
        'setting_customs_duty_rate' => 'Taxa vamală',
        'setting_customs_duty_rate_desc' => 'Taxa vamală în procente (de obicei 0 pentru auto din UE)',
        'setting_hybrid_discount_full' => 'Reducere Full Hybrid',
        'setting_hybrid_discount_full_desc' => 'Reducere pentru Full Hybrid în procente',
        'setting_hybrid_discount_plugin' => 'Reducere Plug-in Hybrid',
        'setting_hybrid_discount_plugin_desc' => 'Reducere pentru Plug-in Hybrid în procente',
        'setting_hybrid_discount_mild' => 'Reducere Mild Hybrid',
        'setting_hybrid_discount_mild_desc' => 'Reducere pentru Mild Hybrid în procente',
        'setting_vintage_30_39_rate' => 'Acciza retro 30-39 ani',
        'setting_vintage_30_39_rate_desc' => 'Acciza fixă pentru auto retro 30-39 ani',
        'setting_vintage_40_49_rate' => 'Acciza retro 40-49 ani',
        'setting_vintage_40_49_rate_desc' => 'Acciza fixă pentru auto retro 40-49 ani',
        'setting_vintage_50_plus_rate' => 'Acciza retro 50+ ani',
        'setting_vintage_50_plus_rate_desc' => 'Acciza fixă pentru auto retro 50+ ani'
    ],
    'ru' => [
        // Calculator page
        'title' => 'Калькулятор Растаможки Авто',
        'eur_rate_label' => 'Курс 1 EUR =',
        'eur_rate_mdl' => 'MDL',
        'save' => 'Сохранить',
        'rate_saved_btn' => 'Сохранено',
        'rate_error_btn' => 'Ошибка',
        'vehicle_type' => 'Тип транспорта',
        'car' => 'Легковой автомобиль',
        'motorcycle' => 'Мотоцикл',
        'truck' => 'Грузовик',
        'year' => 'Год выпуска',
        'capacity' => 'Объём двигателя (см³)',
        'capacity_placeholder' => 'напр: 1998',
        'price_eur' => 'Цена автомобиля (EUR)',
        'price_placeholder' => 'напр: 15000',
        'transport_price' => 'Стоимость доставки (EUR)',
        'transport_placeholder' => 'напр: 500',
        'fuel_type' => 'Тип топлива',
        'gasoline' => 'Бензин',
        'diesel' => 'Дизель',
        'hybrid' => 'Гибрид',
        'electric' => 'Электро',
        'plugin_hybrid' => 'Plug-in Гибрид',
        'full_hybrid' => 'Полный Гибрид',
        'mild_hybrid' => 'Мягкий Гибрид (без скидки)',
        'calculate' => 'Рассчитать',
        'results' => 'Результат расчёта',
        'value_mdl' => 'Таможенная стоимость (MDL)',
        'excise' => 'Акциз',
        'luxury_excise' => 'Акциз люкс',
        'tva' => 'НДС',
        'customs_duty' => 'Сбор за таможенные процедуры',
        'damage_protection' => 'Защита от повреждений (1,2%)',
        'total' => 'ИТОГО РАСХОДЫ НА РАСТАМОЖКУ',
        'vehicle_total' => 'ОБЩАЯ СУММА ЗА АВТОМОБИЛЬ',
        'electric_notice' => 'Электромобили освобождены от акцизов!',
        'electric_notice_sub' => 'Оплачивается только НДС от таможенной стоимости.',
        'usage_stats' => 'Статистика использования',
        'edit_rates' => 'Редактировать ставки',
        
        // Usage page
        'usage_title' => 'Статистика Использования Калькулятора',
        'back_to_calc' => '← Назад к Калькулятору',
        'select_date' => 'Выберите дату',
        'no_usage_data' => 'Нет данных',
        'user' => 'Пользователь',
        'total_uses' => 'Всего',
        'last_use' => 'Последнее',
        
        // Rates page
        'rates_title' => 'Редактирование Ставок Акцизов',
        'general_settings' => 'Общие Настройки',
        'gasoline_rates' => 'Ставки Акцизов - Бензин (MDL/см³)',
        'diesel_rates' => 'Ставки Акцизов - Дизель (MDL/см³)',
        'motorcycle_rates' => 'Ставки Акцизов - Мотоциклы (MDL/см³)',
        'capacity_min' => 'Мин. объём (см³)',
        'capacity_max' => 'Макс. объём (см³)',
        'age_min' => 'Мин. возраст (лет)',
        'age_max' => 'Макс. возраст (лет)',
        'rate' => 'Ставка (MDL/см³)',
        'save_changes' => 'Сохранить изменения',
        'save_success' => 'Изменения успешно сохранены!',
        'save_error' => 'Ошибка при сохранении!',
        
        // Settings labels
        'setting_tva_rate' => 'Ставка НДС',
        'setting_tva_rate_desc' => 'Ставка НДС в процентах',
        'setting_customs_duty_rate' => 'Таможенная пошлина',
        'setting_customs_duty_rate_desc' => 'Таможенная пошлина в процентах (обычно 0 для авто из ЕС)',
        'setting_hybrid_discount_full' => 'Скидка Full Hybrid',
        'setting_hybrid_discount_full_desc' => 'Скидка для Full Hybrid в процентах',
        'setting_hybrid_discount_plugin' => 'Скидка Plug-in Hybrid',
        'setting_hybrid_discount_plugin_desc' => 'Скидка для Plug-in Hybrid в процентах',
        'setting_hybrid_discount_mild' => 'Скидка Mild Hybrid',
        'setting_hybrid_discount_mild_desc' => 'Скидка для Mild Hybrid в процентах',
        'setting_vintage_30_39_rate' => 'Акциз ретро 30-39 лет',
        'setting_vintage_30_39_rate_desc' => 'Фиксированный акциз для ретро авто 30-39 лет',
        'setting_vintage_40_49_rate' => 'Акциз ретро 40-49 лет',
        'setting_vintage_40_49_rate_desc' => 'Фиксированный акциз для ретро авто 40-49 лет',
        'setting_vintage_50_plus_rate' => 'Акциз ретро 50+ лет',
        'setting_vintage_50_plus_rate_desc' => 'Фиксированный акциз для ретро авто 50+ лет'
    ],
    'en' => [
        // Calculator page
        'title' => 'Auto Customs Calculator',
        'eur_rate_label' => 'Rate 1 EUR =',
        'eur_rate_mdl' => 'MDL',
        'save' => 'Save',
        'rate_saved_btn' => 'Saved',
        'rate_error_btn' => 'Error',
        'vehicle_type' => 'Vehicle Type',
        'car' => 'Car',
        'motorcycle' => 'Motorcycle',
        'truck' => 'Truck',
        'year' => 'Year of Production',
        'capacity' => 'Engine Capacity (cm³)',
        'capacity_placeholder' => 'e.g: 1998',
        'price_eur' => 'Vehicle Price (EUR)',
        'price_placeholder' => 'e.g: 15000',
        'transport_price' => 'Transport Price (EUR)',
        'transport_placeholder' => 'e.g: 500',
        'fuel_type' => 'Fuel Type',
        'gasoline' => 'Gasoline',
        'diesel' => 'Diesel',
        'hybrid' => 'Hybrid',
        'electric' => 'Electric',
        'plugin_hybrid' => 'Plug-in Hybrid',
        'full_hybrid' => 'Full Hybrid',
        'mild_hybrid' => 'Mild Hybrid (no discount)',
        'calculate' => 'Calculate',
        'results' => 'Calculation Results',
        'value_mdl' => 'Customs Value (MDL)',
        'excise' => 'Excise',
        'luxury_excise' => 'Luxury excise',
        'tva' => 'VAT',
        'customs_duty' => 'Customs Procedures Fee',
        'damage_protection' => 'Damage Protection (1.2%)',
        'total' => 'TOTAL CUSTOMS COSTS',
        'vehicle_total' => 'TOTAL VEHICLE COST',
        'electric_notice' => 'Electric vehicles are exempt from excise!',
        'electric_notice_sub' => 'Only VAT on customs value is paid.',
        'usage_stats' => 'Usage Statistics',
        'edit_rates' => 'Edit Excise Rates',
        
        // Usage page
        'usage_title' => 'Calculator Usage Statistics',
        'back_to_calc' => '← Back to Calculator',
        'select_date' => 'Select date',
        'no_usage_data' => 'No usage data',
        'user' => 'User',
        'total_uses' => 'Total',
        'last_use' => 'Last Use',
        
        // Rates page
        'rates_title' => 'Edit Excise Rates',
        'general_settings' => 'General Settings',
        'gasoline_rates' => 'Excise Rates - Gasoline (MDL/cm³)',
        'diesel_rates' => 'Excise Rates - Diesel (MDL/cm³)',
        'motorcycle_rates' => 'Excise Rates - Motorcycles (MDL/cm³)',
        'capacity_min' => 'Min Capacity (cm³)',
        'capacity_max' => 'Max Capacity (cm³)',
        'age_min' => 'Min Age (years)',
        'age_max' => 'Max Age (years)',
        'rate' => 'Rate (MDL/cm³)',
        'save_changes' => 'Save Changes',
        'save_success' => 'Changes saved successfully!',
        'save_error' => 'Error saving changes!',
        
        // Settings labels
        'setting_tva_rate' => 'VAT Rate',
        'setting_tva_rate_desc' => 'VAT rate in percentage',
        'setting_customs_duty_rate' => 'Customs Duty',
        'setting_customs_duty_rate_desc' => 'Customs duty rate in percentage (usually 0 for EU cars)',
        'setting_hybrid_discount_full' => 'Full Hybrid Discount',
        'setting_hybrid_discount_full_desc' => 'Discount for Full Hybrid in percentage',
        'setting_hybrid_discount_plugin' => 'Plug-in Hybrid Discount',
        'setting_hybrid_discount_plugin_desc' => 'Discount for Plug-in Hybrid in percentage',
        'setting_hybrid_discount_mild' => 'Mild Hybrid Discount',
        'setting_hybrid_discount_mild_desc' => 'Discount for Mild Hybrid in percentage',
        'setting_vintage_30_39_rate' => 'Vintage 30-39 years excise',
        'setting_vintage_30_39_rate_desc' => 'Fixed excise for vintage cars 30-39 years old',
        'setting_vintage_40_49_rate' => 'Vintage 40-49 years excise',
        'setting_vintage_40_49_rate_desc' => 'Fixed excise for vintage cars 40-49 years old',
        'setting_vintage_50_plus_rate' => 'Vintage 50+ years excise',
        'setting_vintage_50_plus_rate_desc' => 'Fixed excise for vintage cars 50+ years old'
    ]
];

$t = isset($calc_trans[$lang_code]) ? $calc_trans[$lang_code] : $calc_trans['ro'];
