<?php defined( '_DOIT' ) or die( 'Restricted access' );

$lang_code = isset($_COOKIE['lang']) ? $_COOKIE['lang'] : 'ro';

$calc_trans = [
    'ro' => [
        // Calculator page
        'title' => 'Calculator Vămuire Auto',
        'bnm_rate' => 'Curs BNM',
        'vehicle_type' => 'Tipul vehiculului',
        'car' => 'Autoturism',
        'motorcycle' => 'Motocicletă',
        'truck' => 'Camion',
        'year' => 'Anul producerii',
        'capacity' => 'Capacitatea cilindrică (cm³)',
        'capacity_placeholder' => 'ex: 1998',
        'price_eur' => 'Prețul vehiculului (EUR)',
        'price_placeholder' => 'ex: 15000',
        'fuel_type' => 'Tipul combustibilului',
        'gasoline' => 'Benzină',
        'diesel' => 'Diesel',
        'hybrid' => 'Hybrid',
        'electric' => 'Electric',
        'plugin_hybrid' => 'Plug-in Hybrid',
        'full_hybrid' => 'Full Hybrid',
        'mild_hybrid' => 'Mild Hybrid (fără reducere)',
        'calculate' => 'Calculează',
        'results' => 'Rezultatul calculului',
        'value_mdl' => 'Valoarea în vamă (MDL)',
        'excise' => 'Acciza',
        'tva' => 'TVA',
        'customs_duty' => 'Taxă vamală',
        'total' => 'TOTAL COSTURI VĂMUIRE',
        'electric_notice' => 'Vehiculele electrice sunt scutite de accize!',
        'electric_notice_sub' => 'Se achită doar TVA la valoarea în vamă.',
        'usage_stats' => 'Statistici utilizare',
        'edit_rates' => 'Editare cote accize',
        
        // Usage page
        'usage_title' => 'Statistici Utilizare Calculator',
        'back_to_calc' => '← Înapoi la Calculator',
        'no_usage_data' => 'Nu există date de utilizare încă.',
        'user' => 'Utilizator',
        'date' => 'Data',
        'times' => 'Orele utilizării',
        'total_uses' => 'Total utilizări',
        
        // Rates page
        'rates_title' => 'Editare Cote Accize',
        'general_settings' => 'Setări Generale',
        'gasoline_rates' => 'Cote Accize - Benzină (MDL/cm³)',
        'diesel_rates' => 'Cote Accize - Diesel (MDL/cm³)',
        'motorcycle_rates' => 'Cote Accize - Motociclete (MDL/cm³)',
        'capacity_min' => 'Capacitate Min (cm³)',
        'capacity_max' => 'Capacitate Max (cm³)',
        'age_min' => 'Vârstă Min (ani)',
        'age_max' => 'Vârstă Max (ani)',
        'rate' => 'Cotă (MDL/cm³)',
        'save_changes' => 'Salvează modificările',
        'save_success' => 'Modificările au fost salvate cu succes!',
        'save_error' => 'Eroare la salvare!'
    ],
    'ru' => [
        // Calculator page
        'title' => 'Калькулятор Растаможки Авто',
        'bnm_rate' => 'Курс НБМ',
        'vehicle_type' => 'Тип транспорта',
        'car' => 'Легковой автомобиль',
        'motorcycle' => 'Мотоцикл',
        'truck' => 'Грузовик',
        'year' => 'Год выпуска',
        'capacity' => 'Объём двигателя (см³)',
        'capacity_placeholder' => 'напр: 1998',
        'price_eur' => 'Цена автомобиля (EUR)',
        'price_placeholder' => 'напр: 15000',
        'fuel_type' => 'Тип топлива',
        'gasoline' => 'Бензин',
        'diesel' => 'Дизель',
        'hybrid' => 'Гибрид',
        'electric' => 'Электро',
        'plugin_hybrid' => 'Plug-in Гибрид',
        'full_hybrid' => 'Полный Гибрид',
        'mild_hybrid' => 'Мягкий Гибрид (без скидки)',
        'calculate' => 'Рассчитать',
        'results' => 'Результат расчёта',
        'value_mdl' => 'Таможенная стоимость (MDL)',
        'excise' => 'Акциз',
        'tva' => 'НДС',
        'customs_duty' => 'Таможенная пошлина',
        'total' => 'ИТОГО РАСХОДЫ НА РАСТАМОЖКУ',
        'electric_notice' => 'Электромобили освобождены от акцизов!',
        'electric_notice_sub' => 'Оплачивается только НДС от таможенной стоимости.',
        'usage_stats' => 'Статистика использования',
        'edit_rates' => 'Редактировать ставки',
        
        // Usage page
        'usage_title' => 'Статистика Использования Калькулятора',
        'back_to_calc' => '← Назад к Калькулятору',
        'no_usage_data' => 'Данных об использовании пока нет.',
        'user' => 'Пользователь',
        'date' => 'Дата',
        'times' => 'Время использования',
        'total_uses' => 'Всего использований',
        
        // Rates page
        'rates_title' => 'Редактирование Ставок Акцизов',
        'general_settings' => 'Общие Настройки',
        'gasoline_rates' => 'Ставки Акцизов - Бензин (MDL/см³)',
        'diesel_rates' => 'Ставки Акцизов - Дизель (MDL/см³)',
        'motorcycle_rates' => 'Ставки Акцизов - Мотоциклы (MDL/см³)',
        'capacity_min' => 'Мин. объём (см³)',
        'capacity_max' => 'Макс. объём (см³)',
        'age_min' => 'Мин. возраст (лет)',
        'age_max' => 'Макс. возраст (лет)',
        'rate' => 'Ставка (MDL/см³)',
        'save_changes' => 'Сохранить изменения',
        'save_success' => 'Изменения успешно сохранены!',
        'save_error' => 'Ошибка при сохранении!'
    ],
    'en' => [
        // Calculator page
        'title' => 'Auto Customs Calculator',
        'bnm_rate' => 'NBM Rate',
        'vehicle_type' => 'Vehicle Type',
        'car' => 'Car',
        'motorcycle' => 'Motorcycle',
        'truck' => 'Truck',
        'year' => 'Year of Production',
        'capacity' => 'Engine Capacity (cm³)',
        'capacity_placeholder' => 'e.g: 1998',
        'price_eur' => 'Vehicle Price (EUR)',
        'price_placeholder' => 'e.g: 15000',
        'fuel_type' => 'Fuel Type',
        'gasoline' => 'Gasoline',
        'diesel' => 'Diesel',
        'hybrid' => 'Hybrid',
        'electric' => 'Electric',
        'plugin_hybrid' => 'Plug-in Hybrid',
        'full_hybrid' => 'Full Hybrid',
        'mild_hybrid' => 'Mild Hybrid (no discount)',
        'calculate' => 'Calculate',
        'results' => 'Calculation Results',
        'value_mdl' => 'Customs Value (MDL)',
        'excise' => 'Excise',
        'tva' => 'VAT',
        'customs_duty' => 'Customs Duty',
        'total' => 'TOTAL CUSTOMS COSTS',
        'electric_notice' => 'Electric vehicles are exempt from excise!',
        'electric_notice_sub' => 'Only VAT on customs value is paid.',
        'usage_stats' => 'Usage Statistics',
        'edit_rates' => 'Edit Excise Rates',
        
        // Usage page
        'usage_title' => 'Calculator Usage Statistics',
        'back_to_calc' => '← Back to Calculator',
        'no_usage_data' => 'No usage data yet.',
        'user' => 'User',
        'date' => 'Date',
        'times' => 'Usage Times',
        'total_uses' => 'Total Uses',
        
        // Rates page
        'rates_title' => 'Edit Excise Rates',
        'general_settings' => 'General Settings',
        'gasoline_rates' => 'Excise Rates - Gasoline (MDL/cm³)',
        'diesel_rates' => 'Excise Rates - Diesel (MDL/cm³)',
        'motorcycle_rates' => 'Excise Rates - Motorcycles (MDL/cm³)',
        'capacity_min' => 'Min Capacity (cm³)',
        'capacity_max' => 'Max Capacity (cm³)',
        'age_min' => 'Min Age (years)',
        'age_max' => 'Max Age (years)',
        'rate' => 'Rate (MDL/cm³)',
        'save_changes' => 'Save Changes',
        'save_success' => 'Changes saved successfully!',
        'save_error' => 'Error saving changes!'
    ]
];

$t = isset($calc_trans[$lang_code]) ? $calc_trans[$lang_code] : $calc_trans['ro'];
