<?php defined( '_DOIT' ) or die( 'Restricted access' );

/**
 * Frontend B2B translations (ro/ru/en).
 * Self-contained, like crm_lang.php and parsing_lang.php: newer modules in this
 * project carry their own strings instead of extending the global $lng array.
 */

if (!function_exists('b2b_lang')) {

    function b2b_lang_all(): array
    {
        return [
            'ro' => [
                // nav
                'brand'            => 'Cabinet Sauto',
                'cabinet'          => 'Cabinet',
                'cabinet_short'    => 'Cabinet',
                'cabinet_mine'     => 'Cabinetul meu',
                'header_register'  => 'Înregistrare',
                'login'            => 'Autentificare',
                'register'         => 'Înregistrare',
                'logout'           => 'Ieșire',
                'back_to_site'     => 'Înapoi la site',

                // registration form
                'reg_title'        => 'Cont Sauto.md',
                'reg_sub'          => 'Completați datele de contact. Contul devine activ după validarea de către administrator — veți fi anunțat pe email.',
                'person_type'       => 'Tip persoană',
                'person_company'    => 'Persoană juridică',
                'person_individual' => 'Persoană fizică',
                'full_name'         => 'Nume, prenume',
                'login_field'       => 'Login',
                'email'            => 'Email',
                'phone'            => 'Telefon',
                'password'         => 'Parolă',
                'password_repeat'  => 'Repetă parola',
                'password_hint'    => 'Minimum 6 caractere.',
                'pass_show'        => 'Arată parola',
                'pass_hide'        => 'Ascunde parola',
                // Password change (cabinet) / forgot / reset
                'login_forgot'     => 'Ai uitat parola?',
                'pw_change_title'  => 'Schimbă parola',
                'pw_current'       => 'Parola curentă',
                'pw_new'           => 'Parola nouă',
                'pw_new_repeat'    => 'Repetă parola nouă',
                'pw_save'          => 'Schimbă parola',
                'pw_close'         => 'Închide',
                'forgot_email'     => 'Emailul contului',
                'forgot_title'     => 'Resetare parolă',
                'forgot_sub'       => 'Introdu emailul contului. Îți trimitem un link de resetare.',
                'forgot_submit'    => 'Trimite linkul',
                'forgot_back'      => 'Înapoi la autentificare',
                'reset_title'      => 'Setează o parolă nouă',
                'reset_sub'        => 'Alege o parolă nouă pentru contul tău.',
                'reset_submit'     => 'Salvează parola',
                'reset_to_login'   => 'Mergi la autentificare',
                'reset_invalid_ttl'=> 'Link invalid sau expirat',
                'reset_invalid_txt'=> 'Linkul de resetare nu mai e valid. Cere unul nou.',
                'reset_success_ttl'=> 'Parolă schimbată',
                'reset_done_txt'   => 'Parola a fost modificată. Te poți autentifica acum.',
                'login_hint'       => 'Minim 6 caractere',
                'phone_hint'       => '8 cifre, fără prefix. Exemplu: 60 123 456',
                'reg_submit'       => 'Creează cont',
                'reg_have_account' => 'Aveți deja cont?',
                'reg_success_ttl'  => 'Cont creat cu succes',
                'reg_success'      => 'Contul a fost creat cu succes. Te poți autentifica acum.',
                'pass_mismatch'    => 'Parolele nu coincid.',

                // login
                'login_title'      => 'Autentificare cabinet Sauto',
                'login_sub'        => 'Introduceți datele de acces în contul Sauto.md.',
                'login_submit'     => 'Continuă',
                'login_no_account' => 'Nu aveți cont?',

                // cabinet
                'tab_cars'         => 'Favorite',
                'tab_invoices'     => 'Conturi de plată',
                'tab_requests'     => 'Cereri transmise',
                'tab_activity'     => 'Istoric activitate',
                'welcome'          => 'Bine ați venit',
                'status'           => 'Status',
                'regions'          => 'Regiuni permise',
                'no_cars'          => 'Nu aveți încă mașini salvate. Salvați o mașină din catalog pentru a o urmări aici.',
                'saved_cars'       => 'Salvate',
                'viewed_cars'      => 'Vizualizate',
                'no_invoices'      => 'Nu ați generat încă niciun cont de plată.',
                'no_requests'      => 'Nu ați transmis încă nicio cerere.',
                'no_activity'      => 'Nicio activitate înregistrată.',
                'browse_catalog'   => 'Vezi catalogul',
                'invoice_no'       => 'Număr',
                'invoice_car'      => 'Mașină',
                'invoice_amount'   => 'Avans',
                'invoice_date'     => 'Data',
                'invoice_open'     => 'Deschide',
                'req_comment'      => 'Comentariu',
                'req_status'       => 'Status',
                'remove'           => 'Elimină',

                // statuses
                'st_pending'       => 'În așteptare',
                'st_active'        => 'Activ',
                'st_blocked'       => 'Blocat',
                'st_new'           => 'Nouă',
                'st_seen'          => 'Văzută',
                'st_approved'      => 'Aprobată',
                'st_rejected'      => 'Respinsă',
                'st_issued'        => 'Emis',
                'st_sent'          => 'Transmis',
                'st_paid'          => 'Achitat',
                'st_cancelled'     => 'Anulat',

                // regions
                'rg_korea'         => 'Coreea',
                'rg_europe'        => 'Europa',
                'rg_china'         => 'China',
                'rg_usa'           => 'SUA',

                // audit actions
                'ac_login'               => 'Autentificare',
                'ac_login_failed'        => 'Autentificare eșuată',
                'ac_logout'              => 'Ieșire din cont',
                'ac_page_view'           => 'Vizualizare mașină',
                'ac_generate_invoice'    => 'Generare cont de plată',
                'ac_send_to_admin'       => 'Cerere către Super Admin',
                'ac_region_denied'       => 'Acces refuzat pe regiune',
                'ac_save_car'            => 'Mașină salvată',
                'ac_unsave_car'          => 'Mașină eliminată',
                'ac_register'            => 'Cont creat',
                'ac_password_reset'      => 'Parolă schimbată',
                'ac_status_changed'      => 'Status modificat',
                'ac_permissions_changed' => 'Permisiuni modificate',

                // generic errors
                'err_network'      => 'Eroare de rețea. Încercați din nou.',
                'required'         => 'Câmp obligatoriu',
            ],

            'ru' => [
                'brand'            => 'Кабинет Sauto',
                'cabinet'          => 'Кабинет',
                'cabinet_short'    => 'Кабинет',
                'cabinet_mine'     => 'Мой кабинет',
                'header_register'  => 'Регистрация',
                'login'            => 'Вход',
                'register'         => 'Регистрация',
                'logout'           => 'Выход',
                'back_to_site'     => 'Вернуться на сайт',

                'reg_title'        => 'Аккаунт Sauto.md',
                'reg_sub'          => 'Заполните контактные данные. Аккаунт активируется после проверки администратором — мы уведомим вас по email.',
                'person_type'       => 'Тип лица',
                'person_company'    => 'Юридическое лицо',
                'person_individual' => 'Физическое лицо',
                'full_name'         => 'Имя, фамилия',
                'login_field'       => 'Логин',
                'email'            => 'Email',
                'phone'            => 'Телефон',
                'password'         => 'Пароль',
                'password_repeat'  => 'Повторите пароль',
                'password_hint'    => 'Минимум 6 символов.',
                'pass_show'        => 'Показать пароль',
                'pass_hide'        => 'Скрыть пароль',
                // Password change (cabinet) / forgot / reset
                'login_forgot'     => 'Забыли пароль?',
                'pw_change_title'  => 'Сменить пароль',
                'pw_current'       => 'Текущий пароль',
                'pw_new'           => 'Новый пароль',
                'pw_new_repeat'    => 'Повторите новый пароль',
                'pw_save'          => 'Сменить пароль',
                'pw_close'         => 'Закрыть',
                'forgot_email'     => 'Email аккаунта',
                'forgot_title'     => 'Сброс пароля',
                'forgot_sub'       => 'Введите email аккаунта. Мы отправим ссылку для сброса.',
                'forgot_submit'    => 'Отправить ссылку',
                'forgot_back'      => 'Назад ко входу',
                'reset_title'      => 'Задайте новый пароль',
                'reset_sub'        => 'Выберите новый пароль для вашего аккаунта.',
                'reset_submit'     => 'Сохранить пароль',
                'reset_to_login'   => 'Перейти ко входу',
                'reset_invalid_ttl'=> 'Ссылка недействительна или просрочена',
                'reset_invalid_txt'=> 'Ссылка сброса больше недействительна. Запросите новую.',
                'reset_success_ttl'=> 'Пароль изменён',
                'reset_done_txt'   => 'Пароль изменён. Теперь вы можете войти.',
                'login_hint'       => 'Минимум 6 символов',
                'phone_hint'       => '8 цифр, без префикса. Пример: 60 123 456',
                'reg_submit'       => 'Создать аккаунт',
                'reg_have_account' => 'Уже есть аккаунт?',
                'reg_success_ttl'  => 'Аккаунт создан',
                'reg_success'      => 'Аккаунт успешно создан. Теперь вы можете войти.',
                'pass_mismatch'    => 'Пароли не совпадают.',

                'login_title'      => 'Вход в кабинет Sauto',
                'login_sub'        => 'Введите данные доступа к аккаунту Sauto.md.',
                'login_submit'     => 'Продолжить',
                'login_no_account' => 'Нет аккаунта?',

                'tab_cars'         => 'Избранное',
                'tab_invoices'     => 'Счета на оплату',
                'tab_requests'     => 'Отправленные заявки',
                'tab_activity'     => 'История активности',
                'welcome'          => 'Добро пожаловать',
                'status'           => 'Статус',
                'regions'          => 'Доступные регионы',
                'no_cars'          => 'Пока нет сохранённых авто. Сохраните авто из каталога, чтобы следить за ним здесь.',
                'saved_cars'       => 'Сохранённые',
                'viewed_cars'      => 'Просмотренные',
                'no_invoices'      => 'Вы ещё не создавали счетов на оплату.',
                'no_requests'      => 'Вы ещё не отправляли заявок.',
                'no_activity'      => 'Активность не зафиксирована.',
                'browse_catalog'   => 'Смотреть каталог',
                'invoice_no'       => 'Номер',
                'invoice_car'      => 'Автомобиль',
                'invoice_amount'   => 'Аванс',
                'invoice_date'     => 'Дата',
                'invoice_open'     => 'Открыть',
                'req_comment'      => 'Комментарий',
                'req_status'       => 'Статус',
                'remove'           => 'Удалить',

                'st_pending'       => 'Ожидает',
                'st_active'        => 'Активен',
                'st_blocked'       => 'Заблокирован',
                'st_new'           => 'Новая',
                'st_seen'          => 'Просмотрена',
                'st_approved'      => 'Одобрена',
                'st_rejected'      => 'Отклонена',
                'st_issued'        => 'Выставлен',
                'st_sent'          => 'Отправлен',
                'st_paid'          => 'Оплачен',
                'st_cancelled'     => 'Отменён',

                'rg_korea'         => 'Корея',
                'rg_europe'        => 'Европа',
                'rg_china'         => 'Китай',
                'rg_usa'           => 'США',

                'ac_login'               => 'Вход',
                'ac_login_failed'        => 'Неудачный вход',
                'ac_logout'              => 'Выход',
                'ac_page_view'           => 'Просмотр авто',
                'ac_generate_invoice'    => 'Создание счёта',
                'ac_send_to_admin'       => 'Заявка Супер Админу',
                'ac_region_denied'       => 'Отказ по региону',
                'ac_save_car'            => 'Авто сохранено',
                'ac_unsave_car'          => 'Авто удалено',
                'ac_register'            => 'Аккаунт создан',
                'ac_password_reset'      => 'Пароль изменён',
                'ac_status_changed'      => 'Статус изменён',
                'ac_permissions_changed' => 'Права изменены',

                'err_network'      => 'Ошибка сети. Попробуйте ещё раз.',
                'required'         => 'Обязательное поле',
            ],

            'en' => [
                'brand'            => 'Sauto cabinet',
                'cabinet'          => 'Cabinet',
                'cabinet_short'    => 'Cabinet',
                'cabinet_mine'     => 'My cabinet',
                'header_register'  => 'Register',
                'login'            => 'Login',
                'register'         => 'Registration',
                'logout'           => 'Log out',
                'back_to_site'     => 'Back to site',

                'reg_title'        => 'Sauto.md account',
                'reg_sub'          => 'Fill in your contact details. The account is activated after an administrator validates it — you will be notified by email.',
                'person_type'       => 'Person type',
                'person_company'    => 'Legal entity',
                'person_individual' => 'Individual',
                'full_name'         => 'Full name',
                'login_field'       => 'Login',
                'email'            => 'Email',
                'phone'            => 'Phone',
                'password'         => 'Password',
                'password_repeat'  => 'Repeat password',
                'password_hint'    => 'Minimum 6 characters.',
                'pass_show'        => 'Show password',
                'pass_hide'        => 'Hide password',
                // Password change (cabinet) / forgot / reset
                'login_forgot'     => 'Forgot your password?',
                'pw_change_title'  => 'Change password',
                'pw_current'       => 'Current password',
                'pw_new'           => 'New password',
                'pw_new_repeat'    => 'Repeat new password',
                'pw_save'          => 'Change password',
                'pw_close'         => 'Close',
                'forgot_email'     => 'Account email',
                'forgot_title'     => 'Password reset',
                'forgot_sub'       => 'Enter your account email. We will send you a reset link.',
                'forgot_submit'    => 'Send the link',
                'forgot_back'      => 'Back to login',
                'reset_title'      => 'Set a new password',
                'reset_sub'        => 'Choose a new password for your account.',
                'reset_submit'     => 'Save password',
                'reset_to_login'   => 'Go to login',
                'reset_invalid_ttl'=> 'Invalid or expired link',
                'reset_invalid_txt'=> 'The reset link is no longer valid. Request a new one.',
                'reset_success_ttl'=> 'Password changed',
                'reset_done_txt'   => 'Your password was changed. You can log in now.',
                'login_hint'       => 'At least 6 characters',
                'phone_hint'       => '8 digits, without the prefix. Example: 60 123 456',
                'reg_submit'       => 'Create account',
                'reg_have_account' => 'Already have an account?',
                'reg_success_ttl'  => 'Account created',
                'reg_success'      => 'Your account was created successfully. You can log in now.',
                'pass_mismatch'    => 'Passwords do not match.',

                'login_title'      => 'Sauto cabinet login',
                'login_sub'        => 'Enter your Sauto.md account credentials.',
                'login_submit'     => 'Continue',
                'login_no_account' => 'No account yet?',

                'tab_cars'         => 'Favorites',
                'tab_invoices'     => 'Payment invoices',
                'tab_requests'     => 'Sent requests',
                'tab_activity'     => 'Activity log',
                'welcome'          => 'Welcome',
                'status'           => 'Status',
                'regions'          => 'Allowed regions',
                'no_cars'          => 'No saved cars yet. Save a car from the catalog to track it here.',
                'saved_cars'       => 'Saved',
                'viewed_cars'      => 'Viewed',
                'no_invoices'      => 'You have not generated any payment invoice yet.',
                'no_requests'      => 'You have not sent any request yet.',
                'no_activity'      => 'No activity recorded.',
                'browse_catalog'   => 'Browse catalog',
                'invoice_no'       => 'Number',
                'invoice_car'      => 'Car',
                'invoice_amount'   => 'Advance',
                'invoice_date'     => 'Date',
                'invoice_open'     => 'Open',
                'req_comment'      => 'Comment',
                'req_status'       => 'Status',
                'remove'           => 'Remove',

                'st_pending'       => 'Pending',
                'st_active'        => 'Active',
                'st_blocked'       => 'Blocked',
                'st_new'           => 'New',
                'st_seen'          => 'Seen',
                'st_approved'      => 'Approved',
                'st_rejected'      => 'Rejected',
                'st_issued'        => 'Issued',
                'st_sent'          => 'Sent',
                'st_paid'          => 'Paid',
                'st_cancelled'     => 'Cancelled',

                'rg_korea'         => 'Korea',
                'rg_europe'        => 'Europe',
                'rg_china'         => 'China',
                'rg_usa'           => 'USA',

                'ac_login'               => 'Login',
                'ac_login_failed'        => 'Failed login',
                'ac_logout'              => 'Logout',
                'ac_page_view'           => 'Car viewed',
                'ac_generate_invoice'    => 'Invoice generated',
                'ac_send_to_admin'       => 'Request to Super Admin',
                'ac_region_denied'       => 'Region access denied',
                'ac_save_car'            => 'Car saved',
                'ac_unsave_car'          => 'Car removed',
                'ac_register'            => 'Account created',
                'ac_password_reset'      => 'Password changed',
                'ac_status_changed'      => 'Status changed',
                'ac_permissions_changed' => 'Permissions changed',

                'err_network'      => 'Network error. Please try again.',
                'required'         => 'Required field',
            ],
        ];
    }

    /** Strings for the current language, falling back to Romanian. */
    function b2b_lang(?string $lang = null): array
    {
        $lang = $lang ?? ($_COOKIE['lang'] ?? 'ro');
        $all  = b2b_lang_all();
        return $all[$lang] ?? $all['ro'];
    }

    /** One HTML-escaped string. */
    function b2b_t(string $key, ?string $lang = null): string
    {
        $t = b2b_lang($lang);
        return htmlspecialchars($t[$key] ?? $key, ENT_QUOTES, 'UTF-8');
    }
}
