<?php defined( '_DOIT' ) or die( 'Restricted access' );

/**
 * Frontend B2B translations (ro/ru/en).
 * Self-contained, like crm_lang.php and parsing_lang.php: newer modules in this
 * project carry their own strings instead of extending the global $lng array.
 */

if (!function_exists('b2b_lang')) {

    function b2b_lang_all(): array
    {
        return [
            'ro' => [
                // nav
                'brand'            => 'Cabinet Sauto',
                'cabinet'          => 'Cabinet',
                'cabinet_short'    => 'Cabinet',
                'cabinet_mine'     => 'Cabinetul meu',
                'header_register'  => 'Înregistrare',
                'login'            => 'Autentificare',
                'register'         => 'Înregistrare',
                'logout'           => 'Ieșire',
                'back_to_site'     => 'Înapoi la site',

                // registration form
                'reg_title'        => 'Cont Sauto.md',
                'reg_sub'          => 'Înregistrare',
                'person_type'       => 'Tip persoană',
                'person_company'    => 'Persoană juridică',
                'person_individual' => 'Persoană fizică',
                'full_name'         => 'Nume, prenume',
                'email'            => 'Email',
                'phone'            => 'Telefon',
                'password'         => 'Parolă',
                'password_repeat'  => 'Repetă parola',
                'password_hint'    => 'Minimum 6 caractere.',
                'pass_show'        => 'Arată parola',
                'pass_hide'        => 'Ascunde parola',
                // Password change (cabinet) / forgot / reset
                'login_forgot'     => 'Ai uitat parola?',
                'pw_change_title'  => 'Schimbă parola',
                'pw_current'       => 'Parola curentă',
                'pw_new'           => 'Parola nouă',
                'pw_new_repeat'    => 'Repetă parola nouă',
                'pw_save'          => 'Schimbă parola',
                'pw_close'         => 'Închide',
                'forgot_email'     => 'Emailul contului',
                'forgot_title'     => 'Resetare parolă',
                'forgot_sub'       => 'Introdu emailul contului. Îți trimitem un link de resetare.',
                'forgot_submit'    => 'Trimite linkul',
                'forgot_back'      => 'Înapoi la autentificare',
                'reset_title'      => 'Setează o parolă nouă',
                'reset_sub'        => 'Alege o parolă nouă pentru contul tău.',
                'reset_submit'     => 'Salvează parola',
                'reset_to_login'   => 'Mergi la autentificare',
                'reset_invalid_ttl'=> 'Link invalid sau expirat',
                'reset_invalid_txt'=> 'Linkul de resetare nu mai e valid. Cere unul nou.',
                'reset_success_ttl'=> 'Parolă schimbată',
                'reset_done_txt'   => 'Parola a fost modificată. Te poți autentifica acum.',
                'phone_hint'       => '8 cifre, fără prefix. Exemplu: 60 123 456',
                'reg_submit'       => 'Creează cont',
                // No mandatory privacy checkbox: an account is created on the
                // "performance of a contract" basis, so informing is enough.
                'reg_privacy_note' => 'Prin crearea contului, confirmi că ai luat la cunoștință modul în care îți prelucrăm datele, conform',
                'reg_privacy_link' => 'Politicii de Confidențialitate',
                'reg_marketing'    => 'Doresc să primesc oferte, noutăți și alerte auto pe e-mail sau telefon.',
                'reg_have_account' => 'Aveți deja cont?',
                'reg_success_ttl'  => 'Cont creat cu succes',
                'reg_success'      => 'Contul a fost creat cu succes. Te poți autentifica acum.',
                'pass_mismatch'    => 'Parolele nu coincid.',

                // login
                'login_title'      => 'Autentificare cabinet Sauto',
                'login_sub'        => 'Introduceți datele de acces în contul Sauto.md.',
                'login_submit'     => 'Continuă',
                'login_no_account' => 'Nu aveți cont?',

                // cabinet
                'tab_cars'         => 'Favorite',
                'tab_invoices'     => 'Conturi de plată',
                'tab_requests'     => 'Cereri transmise',
                'tab_activity'     => 'Istoric activitate',
                'welcome'          => 'Bine ați venit',
                'status'           => 'Status',
                'regions'          => 'Regiuni permise',
                'no_cars'          => 'Nu aveți încă mașini salvate. Salvați o mașină din catalog pentru a o urmări aici.',
                'saved_cars'       => 'Salvate',
                'viewed_cars'      => 'Vizualizate',
                'no_invoices'      => 'Nu ați generat încă niciun cont de plată.',

                // saved filters (alerts)
                'tab_filters'      => 'Filtrele mele',
                'no_filters'       => 'Nu aveți încă niciun filtru salvat.',
                'flt_new'          => 'Filtru nou',
                'flt_hint'         => 'Salvați filtrul cu mașina dorită și primiți notificare aici și pe email de îndată ce apar mașini noi care se potrivesc.',
                // Shown when the partner declined email contact at signup.
                'flt_hint_nomail'  => 'Salvați filtrul cu mașina dorită și veți primi aici notificare de îndată ce apar mașini noi care se potrivesc.',
                'flt_region'       => 'Sursa',
                'flt_all'          => 'Toate',
                'flt_brand'        => 'Marca',
                'flt_model'        => 'Model',
                'flt_fuel'         => 'Tip motor',
                'flt_gearbox'      => 'Tip cutie',
                'flt_vol_from'     => 'Capacitate de la, cm³',
                'flt_vol_to'       => 'Capacitate până la, cm³',
                'flt_mlg_to'       => 'Parcurs până la, km',
                'flt_year_from'    => 'An de la',
                'flt_year_to'      => 'An până la',
                'flt_price_from'   => 'Preț de la, €',
                'flt_price_to'     => 'Preț până la, €',
                'flt_any'          => 'Oricare',
                'flt_save'         => 'Salvează filtrul',
                'flt_edit'         => 'Modifică filtrul',
                'flt_edit_ttl'     => 'Modificare filtru',
                'flt_update'       => 'Salvează modificările',
                'flt_cancel'       => 'Anulează',
                'flt_delete'       => 'Șterge filtrul',
                'flt_new_cars'     => 'mașini noi',
                'flt_no_new'       => 'Nicio mașină',
                'flt_found'        => 'mașini găsite',
                'flt_from'         => 'de la',
                'flt_to'           => 'până la',

                // recently viewed
                'tab_viewed'       => 'Vizualizate recent',
                'no_viewed'        => 'Nu ați vizitat încă nicio mașină.',

                // gifts
                'tab_gifts'        => 'Cadouri',
                'no_gifts'         => 'Nu aveți încă niciun cadou.',
                'gift_new'         => 'Cadou nou',
                'gift_generic'     => 'Ați primit un cadou',
                'gift_free'        => 'Gratuit la orice automobil achiziționat de la noi',
                'no_requests'      => 'Nu ați transmis încă nicio cerere.',
                'no_activity'      => 'Nicio activitate înregistrată.',
                'browse_catalog'   => 'Vezi catalogul',
                'invoice_no'       => 'Număr',
                'invoice_car'      => 'Mașină',
                'invoice_amount'   => 'Avans',
                'invoice_date'     => 'Data',
                'invoice_open'     => 'Deschide',
                'req_comment'      => 'Comentariu',
                'req_status'       => 'Status',
                'remove'           => 'Elimină',

                // statuses
                'st_pending'       => 'În așteptare',
                'st_active'        => 'Activ',
                'st_blocked'       => 'Blocat',
                'st_new'           => 'Nouă',
                'st_seen'          => 'Văzută',
                'st_approved'      => 'Aprobată',
                'st_rejected'      => 'Respinsă',
                'st_issued'        => 'Emis',
                'st_sent'          => 'Transmis',
                'st_paid'          => 'Achitat',
                'st_cancelled'     => 'Anulat',

                // regions
                'rg_korea'         => 'Coreea',
                'rg_europe'        => 'Europa',
                'rg_china'         => 'China',
                'rg_canada'           => 'Canada',

                // audit actions
                'ac_login'               => 'Autentificare',
                'ac_login_failed'        => 'Autentificare eșuată',
                'ac_logout'              => 'Ieșire din cont',
                'ac_page_view'           => 'Vizualizare mașină',
                'ac_generate_invoice'    => 'Generare cont de plată',
                'ac_send_to_admin'       => 'Cerere către Super Admin',
                'ac_region_denied'       => 'Acces refuzat pe regiune',
                'ac_save_car'            => 'Mașină salvată',
                'ac_unsave_car'          => 'Mașină eliminată',
                'ac_register'            => 'Cont creat',
                'ac_password_reset'      => 'Parolă schimbată',
                'ac_status_changed'      => 'Status modificat',
                'ac_permissions_changed' => 'Permisiuni modificate',

                // generic errors
                'err_network'      => 'Eroare de rețea. Încercați din nou.',
                'required'         => 'Câmp obligatoriu',
            ],

            'ru' => [
                'brand'            => 'Кабинет Sauto',
                'cabinet'          => 'Кабинет',
                'cabinet_short'    => 'Кабинет',
                'cabinet_mine'     => 'Мой кабинет',
                'header_register'  => 'Регистрация',
                'login'            => 'Вход',
                'register'         => 'Регистрация',
                'logout'           => 'Выход',
                'back_to_site'     => 'Вернуться на сайт',

                'reg_title'        => 'Аккаунт Sauto.md',
                'reg_sub'          => 'Регистрация',
                'person_type'       => 'Тип лица',
                'person_company'    => 'Юридическое лицо',
                'person_individual' => 'Физическое лицо',
                'full_name'         => 'Имя, фамилия',
                'email'            => 'Email',
                'phone'            => 'Телефон',
                'password'         => 'Пароль',
                'password_repeat'  => 'Повторите пароль',
                'password_hint'    => 'Минимум 6 символов.',
                'pass_show'        => 'Показать пароль',
                'pass_hide'        => 'Скрыть пароль',
                // Password change (cabinet) / forgot / reset
                'login_forgot'     => 'Забыли пароль?',
                'pw_change_title'  => 'Сменить пароль',
                'pw_current'       => 'Текущий пароль',
                'pw_new'           => 'Новый пароль',
                'pw_new_repeat'    => 'Повторите новый пароль',
                'pw_save'          => 'Сменить пароль',
                'pw_close'         => 'Закрыть',
                'forgot_email'     => 'Email аккаунта',
                'forgot_title'     => 'Сброс пароля',
                'forgot_sub'       => 'Введите email аккаунта. Мы отправим ссылку для сброса.',
                'forgot_submit'    => 'Отправить ссылку',
                'forgot_back'      => 'Назад ко входу',
                'reset_title'      => 'Задайте новый пароль',
                'reset_sub'        => 'Выберите новый пароль для вашего аккаунта.',
                'reset_submit'     => 'Сохранить пароль',
                'reset_to_login'   => 'Перейти ко входу',
                'reset_invalid_ttl'=> 'Ссылка недействительна или просрочена',
                'reset_invalid_txt'=> 'Ссылка сброса больше недействительна. Запросите новую.',
                'reset_success_ttl'=> 'Пароль изменён',
                'reset_done_txt'   => 'Пароль изменён. Теперь вы можете войти.',
                'phone_hint'       => '8 цифр, без префикса. Пример: 60 123 456',
                'reg_submit'       => 'Создать аккаунт',
                'reg_privacy_note' => 'Создавая аккаунт, вы подтверждаете, что ознакомились с тем, как мы обрабатываем ваши данные, согласно',
                'reg_privacy_link' => 'Политике конфиденциальности',
                'reg_marketing'    => 'Хочу получать предложения, новости и автооповещения по e-mail или телефону.',
                'reg_have_account' => 'Уже есть аккаунт?',
                'reg_success_ttl'  => 'Аккаунт создан',
                'reg_success'      => 'Аккаунт успешно создан. Теперь вы можете войти.',
                'pass_mismatch'    => 'Пароли не совпадают.',

                'login_title'      => 'Вход в кабинет Sauto',
                'login_sub'        => 'Введите данные доступа к аккаунту Sauto.md.',
                'login_submit'     => 'Продолжить',
                'login_no_account' => 'Нет аккаунта?',

                'tab_cars'         => 'Избранное',
                'tab_invoices'     => 'Счета на оплату',
                'tab_requests'     => 'Отправленные заявки',
                'tab_activity'     => 'История активности',
                'welcome'          => 'Добро пожаловать',
                'status'           => 'Статус',
                'regions'          => 'Доступные регионы',
                'no_cars'          => 'Пока нет сохранённых авто. Сохраните авто из каталога, чтобы следить за ним здесь.',
                'saved_cars'       => 'Сохранённые',
                'viewed_cars'      => 'Просмотренные',
                'no_invoices'      => 'Вы ещё не создавали счетов на оплату.',

                // saved filters (alerts)
                'tab_filters'      => 'Мои фильтры',
                'no_filters'       => 'У вас пока нет сохранённых фильтров.',
                'flt_new'          => 'Новый фильтр',
                'flt_hint'         => 'Сохраните фильтр с нужным автомобилем — уведомление придёт сюда и на вашу почту, как только добавятся подходящие авто.',
                'flt_hint_nomail'  => 'Сохраните фильтр с нужным автомобилем — и здесь появится уведомление, как только добавятся подходящие авто.',
                'flt_region'       => 'Источник',
                'flt_all'          => 'Все',
                'flt_brand'        => 'Марка',
                'flt_model'        => 'Модель',
                'flt_fuel'         => 'Тип двигателя',
                'flt_gearbox'      => 'Коробка передач',
                'flt_vol_from'     => 'Объём от, см³',
                'flt_vol_to'       => 'Объём до, см³',
                'flt_mlg_to'       => 'Пробег до, км',
                'flt_year_from'    => 'Год от',
                'flt_year_to'      => 'Год до',
                'flt_price_from'   => 'Цена от, €',
                'flt_price_to'     => 'Цена до, €',
                'flt_any'          => 'Любая',
                'flt_save'         => 'Сохранить фильтр',
                'flt_edit'         => 'Изменить фильтр',
                'flt_edit_ttl'     => 'Изменение фильтра',
                'flt_update'       => 'Сохранить изменения',
                'flt_cancel'       => 'Отмена',
                'flt_delete'       => 'Удалить фильтр',
                'flt_new_cars'     => 'новых авто',
                'flt_no_new'       => 'Пока пусто',
                'flt_found'        => 'найдено',
                'flt_from'         => 'от',
                'flt_to'           => 'до',

                // recently viewed
                'tab_viewed'       => 'Недавно просмотренные',
                'no_viewed'        => 'Вы ещё не просматривали ни одного автомобиля.',

                // gifts
                'tab_gifts'        => 'Подарки',
                'no_gifts'         => 'У вас пока нет подарков.',
                'gift_new'         => 'Новый подарок',
                'gift_generic'     => 'Вы получили подарок',
                'gift_free'        => 'Бесплатно при покупке любого автомобиля у нас',
                'no_requests'      => 'Вы ещё не отправляли заявок.',
                'no_activity'      => 'Активность не зафиксирована.',
                'browse_catalog'   => 'Смотреть каталог',
                'invoice_no'       => 'Номер',
                'invoice_car'      => 'Автомобиль',
                'invoice_amount'   => 'Аванс',
                'invoice_date'     => 'Дата',
                'invoice_open'     => 'Открыть',
                'req_comment'      => 'Комментарий',
                'req_status'       => 'Статус',
                'remove'           => 'Удалить',

                'st_pending'       => 'Ожидает',
                'st_active'        => 'Активен',
                'st_blocked'       => 'Заблокирован',
                'st_new'           => 'Новая',
                'st_seen'          => 'Просмотрена',
                'st_approved'      => 'Одобрена',
                'st_rejected'      => 'Отклонена',
                'st_issued'        => 'Выставлен',
                'st_sent'          => 'Отправлен',
                'st_paid'          => 'Оплачен',
                'st_cancelled'     => 'Отменён',

                'rg_korea'         => 'Корея',
                'rg_europe'        => 'Европа',
                'rg_china'         => 'Китай',
                'rg_canada'           => 'Канада',

                'ac_login'               => 'Вход',
                'ac_login_failed'        => 'Неудачный вход',
                'ac_logout'              => 'Выход',
                'ac_page_view'           => 'Просмотр авто',
                'ac_generate_invoice'    => 'Создание счёта',
                'ac_send_to_admin'       => 'Заявка Супер Админу',
                'ac_region_denied'       => 'Отказ по региону',
                'ac_save_car'            => 'Авто сохранено',
                'ac_unsave_car'          => 'Авто удалено',
                'ac_register'            => 'Аккаунт создан',
                'ac_password_reset'      => 'Пароль изменён',
                'ac_status_changed'      => 'Статус изменён',
                'ac_permissions_changed' => 'Права изменены',

                'err_network'      => 'Ошибка сети. Попробуйте ещё раз.',
                'required'         => 'Обязательное поле',
            ],

            'en' => [
                'brand'            => 'Sauto cabinet',
                'cabinet'          => 'Cabinet',
                'cabinet_short'    => 'Cabinet',
                'cabinet_mine'     => 'My cabinet',
                'header_register'  => 'Register',
                'login'            => 'Login',
                'register'         => 'Registration',
                'logout'           => 'Log out',
                'back_to_site'     => 'Back to site',

                'reg_title'        => 'Sauto.md account',
                'reg_sub'          => 'Registration',
                'person_type'       => 'Person type',
                'person_company'    => 'Legal entity',
                'person_individual' => 'Individual',
                'full_name'         => 'Full name',
                'email'            => 'Email',
                'phone'            => 'Phone',
                'password'         => 'Password',
                'password_repeat'  => 'Repeat password',
                'password_hint'    => 'Minimum 6 characters.',
                'pass_show'        => 'Show password',
                'pass_hide'        => 'Hide password',
                // Password change (cabinet) / forgot / reset
                'login_forgot'     => 'Forgot your password?',
                'pw_change_title'  => 'Change password',
                'pw_current'       => 'Current password',
                'pw_new'           => 'New password',
                'pw_new_repeat'    => 'Repeat new password',
                'pw_save'          => 'Change password',
                'pw_close'         => 'Close',
                'forgot_email'     => 'Account email',
                'forgot_title'     => 'Password reset',
                'forgot_sub'       => 'Enter your account email. We will send you a reset link.',
                'forgot_submit'    => 'Send the link',
                'forgot_back'      => 'Back to login',
                'reset_title'      => 'Set a new password',
                'reset_sub'        => 'Choose a new password for your account.',
                'reset_submit'     => 'Save password',
                'reset_to_login'   => 'Go to login',
                'reset_invalid_ttl'=> 'Invalid or expired link',
                'reset_invalid_txt'=> 'The reset link is no longer valid. Request a new one.',
                'reset_success_ttl'=> 'Password changed',
                'reset_done_txt'   => 'Your password was changed. You can log in now.',
                'phone_hint'       => '8 digits, without the prefix. Example: 60 123 456',
                'reg_submit'       => 'Create account',
                'reg_privacy_note' => 'By creating an account you confirm that you have read how we process your data, in accordance with the',
                'reg_privacy_link' => 'Privacy Policy',
                'reg_marketing'    => 'I want to receive offers, news and car alerts by e-mail or phone.',
                'reg_have_account' => 'Already have an account?',
                'reg_success_ttl'  => 'Account created',
                'reg_success'      => 'Your account was created successfully. You can log in now.',
                'pass_mismatch'    => 'Passwords do not match.',

                'login_title'      => 'Sauto cabinet login',
                'login_sub'        => 'Enter your Sauto.md account credentials.',
                'login_submit'     => 'Continue',
                'login_no_account' => 'No account yet?',

                'tab_cars'         => 'Favorites',
                'tab_invoices'     => 'Payment invoices',
                'tab_requests'     => 'Sent requests',
                'tab_activity'     => 'Activity log',
                'welcome'          => 'Welcome',
                'status'           => 'Status',
                'regions'          => 'Allowed regions',
                'no_cars'          => 'No saved cars yet. Save a car from the catalog to track it here.',
                'saved_cars'       => 'Saved',
                'viewed_cars'      => 'Viewed',
                'no_invoices'      => 'You have not generated any payment invoice yet.',

                // saved filters (alerts)
                'tab_filters'      => 'My filters',
                'no_filters'       => 'You have no saved filters yet.',
                'flt_new'          => 'New filter',
                'flt_hint'         => 'Save a filter for the car you want and you will be notified here and by email as soon as matching cars are added.',
                'flt_hint_nomail'  => 'Save a filter for the car you want and you will be notified here as soon as matching cars are added.',
                'flt_region'       => 'Source',
                'flt_all'          => 'All',
                'flt_brand'        => 'Make',
                'flt_model'        => 'Model',
                'flt_fuel'         => 'Engine type',
                'flt_gearbox'      => 'Gearbox',
                'flt_vol_from'     => 'Capacity from, cm³',
                'flt_vol_to'       => 'Capacity to, cm³',
                'flt_mlg_to'       => 'Mileage up to, km',
                'flt_year_from'    => 'Year from',
                'flt_year_to'      => 'Year to',
                'flt_price_from'   => 'Price from, €',
                'flt_price_to'     => 'Price to, €',
                'flt_any'          => 'Any',
                'flt_save'         => 'Save filter',
                'flt_edit'         => 'Edit filter',
                'flt_edit_ttl'     => 'Edit filter',
                'flt_update'       => 'Save changes',
                'flt_cancel'       => 'Cancel',
                'flt_delete'       => 'Delete filter',
                'flt_new_cars'     => 'new cars',
                'flt_no_new'       => 'Nothing yet',
                'flt_found'        => 'cars found',
                'flt_from'         => 'from',
                'flt_to'           => 'to',

                // recently viewed
                'tab_viewed'       => 'Recently viewed',
                'no_viewed'        => 'You have not viewed any car yet.',

                // gifts
                'tab_gifts'        => 'Gifts',
                'no_gifts'         => 'You have no gifts yet.',
                'gift_new'         => 'New gift',
                'gift_generic'     => 'You have received a gift',
                'gift_free'        => 'Free with any car purchased from us',
                'no_requests'      => 'You have not sent any request yet.',
                'no_activity'      => 'No activity recorded.',
                'browse_catalog'   => 'Browse catalog',
                'invoice_no'       => 'Number',
                'invoice_car'      => 'Car',
                'invoice_amount'   => 'Advance',
                'invoice_date'     => 'Date',
                'invoice_open'     => 'Open',
                'req_comment'      => 'Comment',
                'req_status'       => 'Status',
                'remove'           => 'Remove',

                'st_pending'       => 'Pending',
                'st_active'        => 'Active',
                'st_blocked'       => 'Blocked',
                'st_new'           => 'New',
                'st_seen'          => 'Seen',
                'st_approved'      => 'Approved',
                'st_rejected'      => 'Rejected',
                'st_issued'        => 'Issued',
                'st_sent'          => 'Sent',
                'st_paid'          => 'Paid',
                'st_cancelled'     => 'Cancelled',

                'rg_korea'         => 'Korea',
                'rg_europe'        => 'Europe',
                'rg_china'         => 'China',
                'rg_canada'           => 'Canada',

                'ac_login'               => 'Login',
                'ac_login_failed'        => 'Failed login',
                'ac_logout'              => 'Logout',
                'ac_page_view'           => 'Car viewed',
                'ac_generate_invoice'    => 'Invoice generated',
                'ac_send_to_admin'       => 'Request to Super Admin',
                'ac_region_denied'       => 'Region access denied',
                'ac_save_car'            => 'Car saved',
                'ac_unsave_car'          => 'Car removed',
                'ac_register'            => 'Account created',
                'ac_password_reset'      => 'Password changed',
                'ac_status_changed'      => 'Status changed',
                'ac_permissions_changed' => 'Permissions changed',

                'err_network'      => 'Network error. Please try again.',
                'required'         => 'Required field',
            ],
        ];
    }

    /** Strings for the current language, falling back to Romanian. */
    function b2b_lang(?string $lang = null): array
    {
        $lang = $lang ?? ($_COOKIE['lang'] ?? 'ro');
        $all  = b2b_lang_all();
        return $all[$lang] ?? $all['ro'];
    }

    /** One HTML-escaped string. */
    function b2b_t(string $key, ?string $lang = null): string
    {
        $t = b2b_lang($lang);
        return htmlspecialchars($t[$key] ?? $key, ENT_QUOTES, 'UTF-8');
    }
}
